### ISSUE TITLE
Gradle Build is failing...

### ISSUE THREAD

**Issue by leosraj** [UrbanCode/Venafi-UCD#4]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\LeoSelvaraj\Documents\GitHub\Venafi-UCD\build.gradle' line: 57

* What went wrong:
Could not compile build file 'C:\Users\LeoSelvaraj\Documents\GitHub\Venafi-UCD\build.gradle'.
> startup failed:
  build file 'C:\Users\LeoSelvaraj\Documents\GitHub\Venafi-UCD\build.gradle': 57: unexpected token: << @ line 57, column 1.
     <<<<<<< HEAD
     ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

**Comment by jrbarto** [comment]
Resolved with version 29 of the plugin.
